# R OpenSci Unconference 2018 Projects

### `r emo::ji("robot")` [proxy-bias-vignette - Ethical Machine Learning](https://github.com/ropenscilabs/proxy-bias-vignette)

### `r emo::ji("woman_teacher")` [rOpenSciEd - A Community for those who Educate with R](https://github.com/ropenscilabs/rOpenSciEd)

### `r emo::ji("memo")` [pkgreviewr - Automated reports for rOpenSci package reviews](https://github.com/ropenscilabs/pkgreviewr/tree/pkgtests#ropensci-2018-pkgtests-branch)

### `r emo::ji("eye")` [OpenCV - Open Source Computer Vision Library](https://github.com/ropenscilabs/opencv)

### `r emo::ji("old_key")` [middlechild - R interface to MITM](https://github.com/ropenscilabs/middlechild)

### `r emo::ji("shield")` [defender - check code for dangerous calls](https://github.com/ropenscilabs/defender)

### `r emo::ji("secret")` [ropsec - Personal Workstation Safety Checks and Utilities](https://github.com/ropenscilabs/ropsec)

### `r emo::ji("baby")` [mchtoolbox - A toolbox for maternal child health data](https://github.com/ropenscilabs/mchtoolbox)

### `r emo::ji("hot_pepper")` [dataspice - create basic, lightweight and concise metadata files](https://github.com/ropenscilabs/dataspice)

### `r emo::ji("railway_track")` [trackmd - RStudio addin for tracking changes in Markdown format](https://github.com/ropenscilabs/trackmd)

### `r emo::ji("book")`  [QcodeR - Lightweight package to do qualitative coding](https://github.com/ropenscilabs/qcoder)

### `r emo::ji("map")` [umapr - wrapper for `umap` dimensionality reduction algorithm](https://github.com/ropenscilabs/umapr)

### `r emo::ji("press")` [rOpenInterviews - .rprofile and .renviron interview blog series](https://github.com/ropenscilabs/rOpenInterviews)

### `r emo::ji("key")` [keybase - Tools to Work with the Keybase API](https://github.com/ropenscilabs/keybase)

### `r emo::ji("construction_worker_woman")` [jobstatus - Send Job Information Between Functions and Processes](https://github.com/ropenscilabs/jobstatus)

### `r emo::ji("secret")` [ropsec - Operations security for R developers](https://github.com/ropenscilabs/ropsec)

### `r emo::ji("smiling_imp")` [testevil - Package for testing for potentially malicious or unsafe coding practices](https://github.com/ropenscilabs/testevil)

### `r emo::ji("construction_worker_woman")` [greta - simple and scalable statistical modelling in R](https://github.com/ropenscilabs/greta)


---

If there are any projects that you know are missing please
[fork](https://github.com/ropenscilabs/runconf18-projects) 
this document on GitHub, make changes, and then send a pull
request.
